# Dockerfile
# Created on: Jul 2, 2023
# Author: vpatel9202, Assisted by: OpenAI Chatbot
# Link: <insert-link-to-this-chat>

# This Dockerfile is used to build a Docker image for the Google Contacts syncing script.
# It installs the necessary dependencies and sets up the environment to run the script.
